# configs/preprocessing_v2_ft1.yaml
input_dir: "data_v2/raw"            
output_dir: "data_v2/processed"     
overwrite: true                 

target_size: [832, 832] 
padding_color: [114, 114, 114]   
interpolation: "linear"          